---
# tasks file for install_defaults
- name: Install default packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ default_packages }}"
  tags:
    - packages
    - installations

- name: Install eza tool
  include_tasks: install_eza.yml
  tags:
    - eza
