---
- name: Update apt cache
  apt:
    update_cache: yes
  tags: update

- name: Install essential packages
  apt:
    name: "{{ common_packages }}"
    state: present
  when: common_packages is defined
  tags: packages
